# Generated by Django 3.0.7 on 2020-07-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatery_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='https.google.com', upload_to=''),
        ),
    ]
