# Generated by Django 3.0.7 on 2020-07-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatery_backend', '0002_restaurant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='image',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone_number',
            field=models.CharField(default=-5000, max_length=25),
            preserve_default=False,
        ),
    ]
